### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by xyproto** [wayneashleyberry/terminal-dimensions#1]
Does this package also work on Windows?

Asking for a friend.

**Comment by wayneashleyberry** [comment]
I'm not actually sure @xyproto, I have no Windows devices to test on.

**Comment by xyproto** [comment]
No need to have a Windows device.

Tested on wine 5.0 on 64-bit Arch Linux.

# Testing on Wine

## Install Go 1.13.7

```sh
wget 'https://dl.google.com/go/go1.13.7.windows-386.msi'
wine msiexec /i go1.13.7.windows-386.msi
```

Click next next next

## Install Git

```sh
wget 'https://github.com/git-for-windows/git/releases/download/v2.25.0.windows.1/Git-2.25.0-32-bit.exe'
wine Git-2.25.0-32-bit.exe
```

Click next next next

## Clone `terminal-dimensions`

```sh
git clone https://github.com/wayneashleyberry/terminal-dimensions
```

## Launch the Wine command line

```sh
wine cmd
```

## Prepare `GOPATH`

```cmd
md c:\gopath
set GOPATH=c:\gopath
```

## Set the `PATH`

```cmd
set PATH=%PATH%;c:\go\bin;"c:\Program Files (x86)\Git\bin"
```

## Build and test `terminal-dimensions`

```cmd
cd terminal-dimensions
go test
```

The test passes on `wine`, but how can I tell if it correctly detects the terminal dimensions?

**Comment by coreyog** [comment]
Of course it passes the test, the test is a little string manipulation. It doesn't run on Windows because stty is not a thing in cmd.exe.

**Comment by xyproto** [comment]
`stty` on Windows. Why? What's wrong with something like `mode con /status` or `powershell -command "&{$H=get-host;$H.ui.rawui.WindowSize;}"`?
